---
version: "3.8"
services:
  nginx:
    image: nginx:1.21.4
    ports:
      - "8000:80"
  redis:
    image: redis:6.2.6
  redirect:
    image: hsmtkk/supreme-train:latest
    entrypoint: /usr/local/bin/redirect
    environment:
      REDIS_HOST: redis
  short:
    image: hsmtkk/supreme-train:latest
    entrypoint: /usr/local/bin/short
    environment:
      REDIS_HOST: redis
