---
version: "3.8"
services:
  nginx:
    image: nginx:1.21.4
    ports:
      - "8000:80"
  memcached:
    image: memcached:1.6.12
  redirect:
    image: hsmtkk/supreme-train:latest
    entrypoint: /usr/local/bin/redirect
    environment:
      MEMCACHE_HOST: memcached
      MEMCACHE_PORT: 11211
  short:
    image: hsmtkk/supreme-train:latest
    entrypoint: /usr/local/bin/short
    environment:
      MEMCACHE_HOST: memcached
      MEMCACHE_PORT: 11211
