---
name: dockerfile-lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: redirect/Dockerfile short/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
