---
name: docker-build
on: push
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build redirect docker image
        run: docker build . --file redirect/Dockerfile --tag supreme-train:latest
