---
name: workflow
on: [push]
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: redirect/Dockerfile
          ignore: DL3006
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: short/Dockerfile
          ignore: DL3006
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: redirect
        id: redirect
        uses: docker/build-push-action@v2
        with:
          file: redirect/Dockerfile
          push: true
          tags: hsmtkk/supreme-train:redirect-latest
      - name: short
        id: short
        uses: docker/build-push-action@v2
        with:
          file: short/Dockerfile
          push: true
          tags: hsmtkk/supreme-train:short-latest
